### Configuration File
# This is an example configuration file for the split probe design pipeline. Adjust
    # as necessary for your needs.
# These values get loaded into the snakemake as a dictionary in the variable 'config'

## Paths
# Make all of your paths relative to the location where you will execute the snakemake
    # in the command line
input_dir: example_inputs # Path to wherever your 'input_filenames' are
output_dir: outputs # Name of the directory you want to write to,
                        # does not need to exist yet
blast_database: example_database/example.fna # Database to check for off-target binding
flanking_regions_filename: references/split_hcr_flanking_regions.csv # File containing the
                                                                            # readout sequences
pipeline_dir: . # Path to the 'split_probe_design' directory cloned from github

## Inputs
input_filenames: [
                  example.fasta
                  ]
target_seqids_in_blast_db: [] # If the targets are not present in the database leave
                                  # target_seqids_in_blast_db empty. If they are in the
                                  # database, provide a list of the target IDs as they
                                  # are named in the database. This is for the filtering
                                  # step, so that we can remove the on target blast results
target_naming: {'NZ_CP032823.1:785249-786766':'Acr_rrsA',
                'NZ_CP032099.1:c1898141-1896624':'Ask_rrsA',
                'NC_017187.1:c2171088-2169572':'Abu_rrsA'} # Dictionairy specifying easy-to-read
                                                                # names for each target
target_flanking: {'NZ_CP032823.1:785249-786766':'B2',
                  'NZ_CP032099.1:c1898141-1896624':'B2',
                  'NC_017187.1:c2171088-2169572':'B2'} # Assign each target a readout region by
                                                            # referencing an ID from the
                                                            # 'flanking_regions_filename'
## Params
target_alignment_qcovhsp: 50 # Targets are blasted against database. Set the minimum qcovhsp for
                                  # database alignments to be assigned as eqivalent to the target
design_reverse_complement: True # Probes will have the same sequence as the input target, so
                                    # they will hybridize to the reverse complement of the input
                                    # sequence. If you want your probes to hybridize to the input
                                    # sequence, set design_reverse_complement as True.
probe_length: # primer3 input for brute-force designing oligos
    min_size: 18
    opt_size: 20
    max_size: 22
# If you want to design against a double stranded DNA database, set blast_strand
    # to both. If you are only worried about things binding off target to RNA,
    # set strand to minus
blast_strand: both
maximum_pair_distance_bp: 2 # Maximum allowed distance in bases between probe pairs
mch_filter: 12 # Maximum continuous homology for an off-target blast result to not be considered
                    # a strong interaction. Results less than or equal to this value are
                    # ignored, results greater than this value are counted as an off-target
                    # hybridization
tm_filter: 48 # Maximum melting temperature for a blast result to not be considered strong
gc_filter: 7 # Maximum GC count for a blast result to not be considered strong
minimum_bp_between_off_target_sites: 100 # If a left and right probe hybridize off-target at
                                              # a distance from each other (in bases) less
                                              # than this value, then the probe pair will be
                                              # removed
maximum_crosstalk_events: 9 # The maximum number of times a probe pair can have off-target
                                  # interactions with another probe (as defined by
                                  # 'minimum_bp_between_off_target_sites') in the probe set
