### Configuration File
# This is an example configuration file for the split probe design pipeline. Adjust
    # as necessary for your needs.
# These values get loaded into the snakemake as a dictionary in the variable 'config'

## Paths
# Make all of your paths relative to the location where you will execute the snakemake
    # in the command line
input_dir: ../run_003/inputs # Path to wherever your 'input_filenames' are

probe_generate_dir: ../run_003/outputs  # Where to put the brute force primer3 design
target_alignment_dir: outputs/target_alignment
probe_select_dir: outputs/probe_selection
spacer_select_dir: outputs/spacer_selection
crosstalk_dir: outputs/crosstalk
helper_select_dir: outputs/helper_selection
final_outputs_dir: outputs/final_outputs

blast_database: ../../databases/2022_02_15_combined-2021_04_03_contigs-bmg_m/2022_02_15_combined-2021_04_03_contigs-bmg_m.fna # Database to check for off-target binding
flanking_regions_filename: ../../references/split_hcr_flanking_regions.csv # File containing the
                                                                            # readout sequences
pipeline_dir: /workdir/bmg224/hiprfish/probe_design/split_probe_design # Path to the 'split_probe_design' directory cloned from github

## Inputs
input_filenames: [
                  PBG-3104.plaque_mk_m_20210301_.CCS2.0000006459_plus_pstrip_filt_unique_lautropia_pdesign.fasta
                  ]
on_target_id_filename: False
                        # File in input folder containing manually
                        # collected on-target sequence ids in the database
                        # Tab format with columns: sseqid,sstart,send,aln_sub (bool for if we should consider only a subset of that sseqid between sstart,send, or the whole thing).
                        # Otherwise set to False
target_naming: {'bmg_m.29;size=959;':'Lau'}
                                          # Dictionairy specifying easy-to-read
                                                                # names for each target
target_flanking: {'bmg_m.29;size=959;':'B2'}
                                    # Assign each target a readout region by
                                    # referencing an ID from the
                                    # 'flanking_regions_filename'
## Params
target_alignment:
  target_in_db: True  # If you are certain the targets are not present in the database set to false
  min_pident: 80  # Targets are blasted against database. Set minimum percent identity
                  # for database alignments to be assigned as "on-target"
  min_qcovhsp: 30 # Set the minimum query coverage
design_reverse_complement: False # Probes will have the same sequence as the input target, so
                                    # they will hybridize to the reverse complement of the input
                                    # sequence. If you want your probes to hybridize to the input
                                    # sequence, set design_reverse_complement as True.
probe_length: # primer3 input for brute-force designing oligos
    min_size: 18
    opt_size: 20
    max_size: 22
# If you want to design against a double stranded DNA database, set blast_strand
    # to both. If you are only worried about things binding off target to RNA,
    # set strand to minus
blast_strand: both
maximum_pair_distance_bp: 2 # Maximum allowed distance in bases between probe pairs
mch_filter: 12 # Maximum continuous homology for an off-target blast result to not be considered
                    # a strong interaction. Results less than or equal to this value are
                    # ignored, results greater than this value are counted as an off-target
                    # hybridization
tm_filter: 48 # Maximum melting temperature for a blast result to not be considered strong
gc_filter: 7 # Maximum GC count for a blast result to not be considered strong
minimum_bp_between_off_target_sites: 500 # If a left and right probe hybridize off-target at
                                              # a distance from each other (in bases) less
                                              # than this value, then the probe pair will be
                                              # removed
maximum_crosstalk_events: 9 # The maximum number of times a probe pair can have off-target
                                  # interactions with another probe (as defined by
                                  # 'minimum_bp_between_off_target_sites') in the probe set
select_alternate_design: False  # Pairs are selected to minimize the left probe off target results
                                # unless this is set to True, in which case the right probes are minimized
get_helpers:
    same_strand: True  # If True, design probes without flanking regions and without specificit
    other_strand: False  # If True, design helper probes for the reverse complement
                            # strand as well as the gaps in the probe strand
